package org.howard.edu.lsp.finalexam.question2;

/**
 * Strategy interface for random number generation.
 * 
 * <p>All random number generation strategies must implement this interface.</p>
 * 
 * @author Oluwaseun Noah Adeyeye
 * @version 1.0
 */
public interface RandomNumberStrategy {
    /**
     * Generates a random positive integer.
     * 
     * @return A positive integer generated by the strategy.
     */
    int generate();
}
